window.AGE_GAME_DATA = (() => {
const GAME_CONFIG = {
  appName: "The Age Game",
  yearMin: 1900,
  yearMax: 2026,
  defaultGuessYear: 1963,
  hintsEnabled: false,
  revealExplanationEnabled: true,
  aiModeEnabled: true,
  uploadsEnabled: true,
  seedObjectsEnabled: true,
  supabase: {
    enabled: true,
    url: "https://eijahowxbexgqplhniud.supabase.co",
    anonKey: "sb_publishable_XOE_q17kbn2FjIVxaptwAA_Nlsq94Xq",
    objectsTable: "objects",
    storageBucket: "object-images",
  },
  localStorageKeys: {
    uploads: "age-game:v1:uploads",
    daily: "age-game:v1:daily-results",
  },
  olderNewerDifficulty: {
    easy: { minGap: 20, maxGap: 126 },
    medium: { minGap: 8, maxGap: 25 },
    hard: { minGap: 1, maxGap: 7 },
  },
  categories: ["Tech", "Media", "Home", "Cameras", "Fashion", "Toys", "Tools", "Packaging", "Transportation"],
};

const MODES = [
  {
    id: "timeline",
    label: "Timeline",
    shortLabel: "Timeline",
  },
  {
    id: "olderNewer",
    label: "Older / Newer",
    shortLabel: "Older",
  },
  {
    id: "daily",
    label: "Daily Artifact",
    shortLabel: "Daily",
  },
  {
    id: "submit",
    label: "Submit an Object",
    shortLabel: "Submit",
  },
  {
    id: "imagined",
    label: "Imagined Era",
    shortLabel: "Imagined",
  },
];

const OBJECTS = [
  {
    id: "hand-crank-telephone-1905",
    title: "Hand-Crank Wall Telephone",
    brand: "Exchange Bell",
    category: "Tech",
    yearStart: 1903,
    yearEnd: 1908,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["telephone", "crank", "wood", "early-1900s"],
    revealText:
      "A hand crank, wall-mounted body, and early telephone exchange styling point to the first decade of the 1900s.",
    hints: [
      "This is before rotary dialing.",
      "The crank is the main era clue.",
    ],
    asset: {
      shape: "rotary-phone",
      primary: "#4B3326",
      secondary: "#C8A46B",
      accent: "#2B3036",
      label: "CALL",
      detail: "EXCHANGE",
    },
  },
  {
    id: "stand-mixer-1952",
    title: "Enamel Stand Mixer",
    brand: "Homecraft",
    category: "Home",
    yearStart: 1951,
    yearEnd: 1954,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["kitchen", "appliance", "enamel", "chrome"],
    revealText:
      "Rounded enamel appliances, chrome accents, and chunky controls are strong early-1950s kitchen signals.",
    hints: [
      "Look at the enamel body and chrome trim.",
      "The silhouette predates compact plastic appliance design.",
    ],
    asset: {
      shape: "mixer",
      primary: "#E84A3A",
      secondary: "#F7F1DF",
      accent: "#3E7D80",
      label: "MIX",
      detail: "10 SPEED",
    },
  },
  {
    id: "pocket-radio-1957",
    title: "Pocket Transistor Radio",
    brand: "Signal",
    category: "Media",
    yearStart: 1956,
    yearEnd: 1959,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["radio", "transistor", "portable"],
    revealText:
      "The tiny speaker grille, analog tuning window, and early portable electronics styling point to the late 1950s.",
    hints: [
      "This is after vacuum-tube sets, but before cassette portability.",
      "The tuning scale is fully analog.",
    ],
    asset: {
      shape: "radio",
      primary: "#D0473F",
      secondary: "#F6E6B6",
      accent: "#202533",
      label: "AM",
      detail: "640 800 1200",
    },
  },
  {
    id: "tailfin-key-1959",
    title: "Tailfin Car Key",
    brand: "Aster",
    category: "Tools",
    yearStart: 1958,
    yearEnd: 1961,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "hard",
    tags: ["car", "key", "chrome", "tailfin"],
    revealText:
      "The decorative head shape borrows from tailfin-era automotive styling, a late-1950s cue.",
    hints: [
      "The object borrows its shape from car design trends.",
      "Think chrome, fins, and optimistic postwar styling.",
    ],
    asset: {
      shape: "car-key",
      primary: "#D6DEE5",
      secondary: "#B8C4CC",
      accent: "#E44D3A",
      label: "V8",
      detail: "AUTO",
    },
  },
  {
    id: "rotary-phone-1964",
    title: "Rotary Desk Phone",
    brand: "Bellline",
    category: "Home",
    yearStart: 1962,
    yearEnd: 1966,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["phone", "rotary", "bakelite"],
    revealText:
      "The rotary dial and heavy molded handset put this squarely before push-button phones became common.",
    hints: [
      "The input method is mechanical.",
      "The handset shape is still heavy and desk-bound.",
    ],
    asset: {
      shape: "rotary-phone",
      primary: "#2E3238",
      secondary: "#E7E0C7",
      accent: "#C74738",
      label: "0",
      detail: "DIAL",
    },
  },
  {
    id: "instant-camera-1968",
    title: "Folding Instant Camera",
    brand: "Flashmat",
    category: "Cameras",
    yearStart: 1967,
    yearEnd: 1970,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["camera", "instant", "folding"],
    revealText:
      "Folding bellows, a large front lens, and instant-print proportions are late-1960s camera cues.",
    hints: [
      "The object prints immediately but still uses a mechanical folding body.",
      "The front face is much larger than later pocket cameras.",
    ],
    asset: {
      shape: "instant-camera",
      primary: "#2C2F35",
      secondary: "#A4744B",
      accent: "#F2B84B",
      label: "COLOR",
      detail: "INSTANT",
    },
  },
  {
    id: "desk-calculator-1972",
    title: "Red LED Desk Calculator",
    brand: "Digitron",
    category: "Tech",
    yearStart: 1971,
    yearEnd: 1974,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["calculator", "led", "office"],
    revealText:
      "Red LED digits and tall physical keys place this near the early consumer calculator boom.",
    hints: [
      "The display is red LED, not LCD.",
      "The keypad is tall and office-like.",
    ],
    asset: {
      shape: "calculator",
      primary: "#3B3A36",
      secondary: "#D2C5A1",
      accent: "#FF4C3E",
      label: "8008",
      detail: "MEM",
    },
  },
  {
    id: "joystick-1977",
    title: "Cartridge Console Joystick",
    brand: "Vector Play",
    category: "Toys",
    yearStart: 1977,
    yearEnd: 1980,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["game", "joystick", "console"],
    revealText:
      "A single stick, one red button, and boxy home-console design make this a late-1970s object.",
    hints: [
      "One button is the whole interface.",
      "The form belongs to early cartridge gaming.",
    ],
    asset: {
      shape: "joystick",
      primary: "#15181D",
      secondary: "#F5A623",
      accent: "#D83B2E",
      label: "TV GAME",
      detail: "FIRE",
    },
  },
  {
    id: "cassette-player-1980",
    title: "Portable Cassette Player",
    brand: "MetroSound",
    category: "Media",
    yearStart: 1979,
    yearEnd: 1982,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["cassette", "portable", "music"],
    revealText:
      "Metal trim, mechanical transport buttons, and cassette portability put this at the start of the 1980s.",
    hints: [
      "This object makes music portable before discs.",
      "Mechanical buttons are still part of the main interface.",
    ],
    asset: {
      shape: "cassette-player",
      primary: "#BAC4C7",
      secondary: "#23262B",
      accent: "#F2A33A",
      label: "STEREO",
      detail: "AUTO STOP",
    },
  },
  {
    id: "camcorder-1983",
    title: "Shoulder Camcorder",
    brand: "Vistacam",
    category: "Cameras",
    yearStart: 1982,
    yearEnd: 1985,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["video", "camcorder", "tape"],
    revealText:
      "The long shoulder body and tape-era proportions are classic early-1980s home video design.",
    hints: [
      "This is home video before compact palm camcorders.",
      "Its size is part of the era clue.",
    ],
    asset: {
      shape: "camcorder",
      primary: "#252B31",
      secondary: "#646E78",
      accent: "#E34C3C",
      label: "VIDEO 8",
      detail: "REC",
    },
  },
  {
    id: "discman-1985",
    title: "Portable CD Player",
    brand: "Orbital Audio",
    category: "Media",
    yearStart: 1984,
    yearEnd: 1987,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["cd", "portable", "audio"],
    revealText:
      "Early compact-disc branding, a round lid, and physical transport buttons point to the mid-1980s.",
    hints: [
      "It is after cassettes became portable.",
      "The media format is optical.",
    ],
    asset: {
      shape: "discman",
      primary: "#D9DEE2",
      secondary: "#2E343B",
      accent: "#44A0A8",
      label: "COMPACT DISC",
      detail: "16 BIT",
    },
  },
  {
    id: "hi-top-sneaker-1987",
    title: "Color Block High-Top Sneaker",
    brand: "Courtline",
    category: "Fashion",
    yearStart: 1986,
    yearEnd: 1989,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["sneaker", "fashion", "basketball"],
    revealText:
      "High-top basketball proportions and bold color blocking are late-1980s streetwear signals.",
    hints: [
      "The silhouette is tied to basketball culture.",
      "The color blocking is louder than early-1980s sportswear.",
    ],
    asset: {
      shape: "sneaker",
      primary: "#F7F5ED",
      secondary: "#1D1F26",
      accent: "#E23E35",
      label: "AIR",
      detail: "HI",
    },
  },
  {
    id: "brick-phone-1989",
    title: "Portable Brick Phone",
    brand: "Cellstar",
    category: "Tech",
    yearStart: 1988,
    yearEnd: 1991,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["phone", "mobile", "antenna"],
    revealText:
      "Large size, exposed antenna, and physical number keys put this before smaller 1990s handsets.",
    hints: [
      "Mobile, but not yet pocket friendly.",
      "The antenna is not subtle.",
    ],
    asset: {
      shape: "brick-phone",
      primary: "#2B3036",
      secondary: "#C0C6C8",
      accent: "#6EC1A6",
      label: "CELL",
      detail: "SEND END",
    },
  },
  {
    id: "pager-1993",
    title: "Numeric Pager",
    brand: "Beeper Co.",
    category: "Tech",
    yearStart: 1992,
    yearEnd: 1995,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["pager", "lcd", "belt"],
    revealText:
      "A small LCD, belt-clip body, and numeric messaging belong to the early-to-mid 1990s.",
    hints: [
      "It receives tiny messages before smartphones.",
      "It was often clipped onto clothing.",
    ],
    asset: {
      shape: "pager",
      primary: "#24282E",
      secondary: "#9BC1A6",
      accent: "#D4A33B",
      label: "555-0198",
      detail: "PAGE",
    },
  },
  {
    id: "vhs-tape-1995",
    title: "Rental VHS Cassette",
    brand: "Night Owl Video",
    category: "Media",
    yearStart: 1994,
    yearEnd: 1997,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["vhs", "rental", "video"],
    revealText:
      "Rental labels, magnetic tape windows, and home-video store cues land this in the mid-1990s.",
    hints: [
      "The object belongs to a rental-store ritual.",
      "The format is magnetic tape.",
    ],
    asset: {
      shape: "vhs",
      primary: "#181C21",
      secondary: "#ECE3CE",
      accent: "#2D8AA0",
      label: "BE KIND REWIND",
      detail: "VHS",
    },
  },
  {
    id: "translucent-desktop-1998",
    title: "Translucent Desktop Computer",
    brand: "Blueberry Works",
    category: "Tech",
    yearStart: 1998,
    yearEnd: 2000,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["computer", "translucent", "desktop"],
    revealText:
      "Translucent colored plastic and all-in-one consumer computer styling are late-1990s signatures.",
    hints: [
      "The casing is meant to be seen through.",
      "This was a friendly consumer computer look.",
    ],
    asset: {
      shape: "desktop",
      primary: "#6EC7D1",
      secondary: "#EAF7F7",
      accent: "#F3A23A",
      label: "hello",
      detail: "USB",
    },
  },
  {
    id: "mp3-player-2002",
    title: "White Pocket Music Player",
    brand: "PocketBeat",
    category: "Media",
    yearStart: 2001,
    yearEnd: 2004,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["mp3", "music", "digital"],
    revealText:
      "A tiny screen, white plastic, and click-wheel style controls point to the early digital music-player era.",
    hints: [
      "This object stores songs, not discs or tapes.",
      "The interface is built around a wheel.",
    ],
    asset: {
      shape: "mp3-player",
      primary: "#F9F7F0",
      secondary: "#BFC8CF",
      accent: "#7A8C9A",
      label: "1,024 songs",
      detail: "MENU",
    },
  },
  {
    id: "flip-phone-2005",
    title: "Slim Flip Phone",
    brand: "Razrline",
    category: "Tech",
    yearStart: 2004,
    yearEnd: 2006,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["phone", "flip", "mobile"],
    revealText:
      "The thin clamshell body and metallic keypad are mid-2000s mobile phone clues.",
    hints: [
      "The design celebrates thinness before touchscreens dominate.",
      "It opens to reveal the main controls.",
    ],
    asset: {
      shape: "flip-phone",
      primary: "#50545C",
      secondary: "#BFC5CC",
      accent: "#45A6A7",
      label: "CAM",
      detail: "MENU",
    },
  },
  {
    id: "dslr-2007",
    title: "Entry DSLR Camera",
    brand: "Framewell",
    category: "Cameras",
    yearStart: 2006,
    yearEnd: 2009,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "hard",
    tags: ["camera", "dslr", "digital"],
    revealText:
      "A consumer DSLR body, mode dial, and small rear screen place it in the late-2000s digital camera wave.",
    hints: [
      "This is after film SLRs became niche for consumers.",
      "The rear screen is present but not huge.",
    ],
    asset: {
      shape: "dslr",
      primary: "#1B1E23",
      secondary: "#343A43",
      accent: "#D74B3F",
      label: "10.2 MP",
      detail: "AUTO",
    },
  },
  {
    id: "touch-phone-2008",
    title: "First-Wave Touch Smartphone",
    brand: "Glassline",
    category: "Tech",
    yearStart: 2007,
    yearEnd: 2010,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "easy",
    tags: ["smartphone", "touchscreen", "apps"],
    revealText:
      "A large glass screen, minimal front controls, and app-grid layout define the late-2000s smartphone shift.",
    hints: [
      "The front is dominated by a screen.",
      "This is after flip phones, before edge-to-edge displays.",
    ],
    asset: {
      shape: "smartphone",
      primary: "#11151B",
      secondary: "#F7F8F8",
      accent: "#5DADEC",
      label: "apps",
      detail: "3G",
    },
  },
  {
    id: "e-reader-2011",
    title: "E-Ink Reader",
    brand: "PageLite",
    category: "Tech",
    yearStart: 2010,
    yearEnd: 2012,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["reader", "tablet", "e-ink"],
    revealText:
      "An e-ink screen with chunky bezels and page buttons points to the early 2010s e-reader boom.",
    hints: [
      "It is digital, but not a general-purpose tablet.",
      "The screen is built for reading.",
    ],
    asset: {
      shape: "ereader",
      primary: "#ECEDE7",
      secondary: "#B9BDB4",
      accent: "#2C3338",
      label: "Chapter 1",
      detail: "E-INK",
    },
  },
  {
    id: "smartwatch-2015",
    title: "Rounded Smartwatch",
    brand: "WristOS",
    category: "Fashion",
    yearStart: 2014,
    yearEnd: 2016,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["watch", "smartwatch", "wearable"],
    revealText:
      "A touchscreen watch face, fitness rings, and minimal digital case language point to the mid-2010s.",
    hints: [
      "It is worn like a watch, but behaves like a tiny computer.",
      "The fitness UI is a key cue.",
    ],
    asset: {
      shape: "smartwatch",
      primary: "#252A31",
      secondary: "#E7E9EA",
      accent: "#48B582",
      label: "09:41",
      detail: "MOVE",
    },
  },
  {
    id: "wireless-earbuds-2017",
    title: "True Wireless Earbuds",
    brand: "Airwave",
    category: "Media",
    yearStart: 2016,
    yearEnd: 2018,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["earbuds", "wireless", "audio"],
    revealText:
      "Stemmed wireless buds and a tiny charging case are clear late-2010s personal audio signals.",
    hints: [
      "The cable is gone.",
      "The case is part charger, part storage.",
    ],
    asset: {
      shape: "earbuds",
      primary: "#F9FAF7",
      secondary: "#D9E0E4",
      accent: "#5AA8A7",
      label: "L R",
      detail: "BT",
    },
  },
  {
    id: "smart-speaker-2019",
    title: "Fabric Voice Speaker",
    brand: "Nestory",
    category: "Home",
    yearStart: 2018,
    yearEnd: 2020,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "hard",
    tags: ["speaker", "voice", "home"],
    revealText:
      "Fabric mesh, tiny status LEDs, and voice-assistant minimalism fit the late-2010s smart-home wave.",
    hints: [
      "It is designed to disappear into a room.",
      "The interface is mostly voice.",
    ],
    asset: {
      shape: "smart-speaker",
      primary: "#D3D7D3",
      secondary: "#7B8588",
      accent: "#F0B240",
      label: "ASK",
      detail: "VOICE",
    },
  },
  {
    id: "ring-light-2020",
    title: "Creator Ring Light",
    brand: "Lumina",
    category: "Tools",
    yearStart: 2020,
    yearEnd: 2022,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["creator", "light", "video"],
    revealText:
      "Phone mounting, compact studio lighting, and creator-workflow design place this around the early 2020s.",
    hints: [
      "This object supports phone-first video creation.",
      "The ring shape is meant for faces on camera.",
    ],
    asset: {
      shape: "ring-light",
      primary: "#F4F1E7",
      secondary: "#242A31",
      accent: "#67B7C8",
      label: "LIVE",
      detail: "5600K",
    },
  },
  {
    id: "handheld-pc-2023",
    title: "Handheld Gaming PC",
    brand: "Deckforge",
    category: "Toys",
    yearStart: 2022,
    yearEnd: 2024,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["game", "handheld", "pc"],
    revealText:
      "Large grips, twin sticks, and PC-style handheld gaming point to the early-to-mid 2020s.",
    hints: [
      "It is larger than classic handheld consoles.",
      "It borrows from PC gaming and console controls.",
    ],
    asset: {
      shape: "handheld",
      primary: "#252A33",
      secondary: "#0D1117",
      accent: "#46B3A7",
      label: "LIBRARY",
      detail: "120Hz",
    },
  },
  {
    id: "usb-c-phone-2024",
    title: "USB-C Glass Smartphone",
    brand: "Monolith",
    category: "Tech",
    yearStart: 2023,
    yearEnd: 2026,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "hard",
    tags: ["smartphone", "usb-c", "camera"],
    revealText:
      "Nearly full-screen glass, a large camera island, and USB-C era cues point to the mid-2020s.",
    hints: [
      "The screen leaves very little bezel.",
      "The port standard is a recent clue.",
    ],
    asset: {
      shape: "smartphone",
      primary: "#171A20",
      secondary: "#F2F6F6",
      accent: "#B84DEB",
      label: "USB-C",
      detail: "5G",
    },
  },
  {
    id: "chrome-car-radio-1965",
    title: "Chrome Car Radio",
    brand: "Roadtone",
    category: "Transportation",
    yearStart: 1964,
    yearEnd: 1967,
    sourceType: "curated",
    imageType: "illustration",
    difficulty: "medium",
    tags: ["car", "dashboard", "radio", "chrome"],
    revealText:
      "Chrome knobs, analog station markings, and dashboard proportions point to mid-1960s transportation interiors.",
    hints: [
      "This object belongs inside a vehicle dashboard.",
      "The radio tuning style is analog and chrome-heavy.",
    ],
    asset: {
      shape: "radio",
      primary: "#C9D0D4",
      secondary: "#232A31",
      accent: "#D9513D",
      label: "AM FM",
      detail: "ROAD",
    },
  },
  {
    id: "imagined-atomic-lamp-1962",
    title: "Imagined Atomic Desk Lamp",
    brand: "AI Study",
    category: "Home",
    yearStart: 1961,
    yearEnd: 1965,
    sourceType: "imagined",
    imageType: "ai-concept",
    difficulty: "medium",
    tags: ["imagined", "lamp", "atomic", "home"],
    revealText:
      "This imagined object leans on atomic-age angles, brass feet, and warm plastic common to early-1960s interiors.",
    hints: [
      "The styling borrows from space-age domestic design.",
      "Think early 1960s optimism rather than late 1970s utility.",
    ],
    asset: {
      shape: "atomic-lamp",
      primary: "#F1C64B",
      secondary: "#335C67",
      accent: "#D94F3D",
      label: "ATOM",
      detail: "DESK",
    },
  },
  {
    id: "imagined-clear-pda-1999",
    title: "Imagined Clear-Shell PDA",
    brand: "AI Study",
    category: "Tech",
    yearStart: 1998,
    yearEnd: 2001,
    sourceType: "imagined",
    imageType: "ai-concept",
    difficulty: "medium",
    tags: ["imagined", "pda", "translucent"],
    revealText:
      "The transparent shell, stylus slot, and pocket-organizer screen combine late-1990s design cues.",
    hints: [
      "Clear plastic is the loudest clue.",
      "It is a pocket computer before smartphones take over.",
    ],
    asset: {
      shape: "pda",
      primary: "#7FD2E0",
      secondary: "#E8F7F9",
      accent: "#F4A940",
      label: "TO DO",
      detail: "SYNC",
    },
  },
  {
    id: "imagined-vlog-cube-2018",
    title: "Imagined Pocket Vlog Cube",
    brand: "AI Study",
    category: "Cameras",
    yearStart: 2017,
    yearEnd: 2020,
    sourceType: "imagined",
    imageType: "ai-concept",
    difficulty: "hard",
    tags: ["imagined", "camera", "creator"],
    revealText:
      "A tiny action-camera body, clip mount, and creator-first controls make this feel late-2010s.",
    hints: [
      "It assumes everyday video sharing.",
      "The form is smaller and more modular than older camcorders.",
    ],
    asset: {
      shape: "vlog-cube",
      primary: "#F2F2EC",
      secondary: "#20242B",
      accent: "#EF5B45",
      label: "4K",
      detail: "LIVE",
    },
  },
  {
    id: "imagined-ai-pin-2026",
    title: "Imagined AI Lapel Pin",
    brand: "AI Study",
    category: "Tech",
    yearStart: 2024,
    yearEnd: 2026,
    sourceType: "imagined",
    imageType: "ai-concept",
    difficulty: "hard",
    tags: ["imagined", "ai", "wearable"],
    revealText:
      "A screenless wearable, mic grille, and assistant-first design language point to the mid-2020s.",
    hints: [
      "It tries to replace a phone interaction with a wearable assistant.",
      "The clue is the absence of a normal screen.",
    ],
    asset: {
      shape: "ai-pin",
      primary: "#191C22",
      secondary: "#ECEEEB",
      accent: "#7D5CFF",
      label: "AI",
      detail: "VOICE",
    },
  },
];

return {
  GAME_CONFIG,
  MODES,
  OBJECTS,
};
})();
